### ISSUE TITLE
Multiphase rollout of reagent tracking / multi-reagent prep

### ISSUE THREAD

**Issue by ipendlet** [darkreactions/ESCALATE_Capture#92]
Tied to https://github.com/darkreactions/ESCALATE_report/issues/49

The purpose of this update is to provide the ability to specify past reagent-objects as starting materials for reactions as well as using reagents as inputs for precursor/reagent solutions.  This will have limited support, but increase over time.  The update will eventually improve the relationship between historical samples and to increase the underlying relationship to the original ESCALATE data model. 

Due to timelines (need to get alloys out this update will have to come in waves).  

First Push / Merge Goal:
- [x]     1.  Update reagent model dictionary to hold reagents of the type 'solvent' -- ONLY SOLVENTS.  The solvents can just be assumed for the first pass and directly read into the interface.  
- [x]     2. A solvent can be prepared via the “notes” section (hard-coded instructions and a unique dictionary which is pushed directly to the json backend for later parsing -- a new section for 'incoming reagents' dictionary, which can be used to unpack as needed for the first pass.  The exact details of the solvent object are not essential to early development.  Only bare bones information is needed
- [x]     3. Use the user defined names (no UID) for the solvent amount.  (eventually think about reagent-model reagent-object UID
- [x]     4. Amounts simple: if you know amount of A:B and dispense C, you can calculate the amounts of A and B in the final rxn mixture (at least in terms of mmol).  The solvent ideality approximation (we assume that two solvents mixing volume is their sum) can be applied to the solvent mixing but should be WARNED to user similar to the existing warning system.
- [x]     5. Improve documentation for code that this touches.  Try to leave as abstracted as possible from the larger dictionaries in the code.  
- [x]     5. Test and deploy 1
